import type { Route } from "./+types/privacy";
import { LegalPage } from "../components/legal/legal-page";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Privacy | Zamar Relief" },
    {
      name: "description",
      content:
        "Privacy information for Zamar Relief and the Zamar Field open-source project.",
    },
  ];
}

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy policy" updatedAt="16 May 2026">
      <p>
        Zamar Relief is an independent humanitarian initiative in progress. This
        website is a simple public information space, and Zamar Field is an
        open-source project built to support offline field data collection.
      </p>
      <h2>What we collect</h2>
      <p>
        This website currently does not offer user accounts, public uploads, or
        production contact forms. We may receive limited technical information
        normally generated by web hosting, such as server logs, page requests,
        browser metadata, and basic security signals.
      </p>
      <h2>Zamar Field project data</h2>
      <p>
        Zamar Field is being designed for field teams working in sensitive and
        low-connectivity contexts. The app may process records such as location,
        notes, images, interviews, and other operational data, but this website
        does not itself collect or store that field information.
      </p>
      <ul>
        <li>Field records should remain controlled by the operators using the app.</li>
        <li>Offline-first storage is preferred when it reduces operational risk.</li>
        <li>Data handling practices may evolve as the project matures.</li>
      </ul>
      <h2>Open-source transparency</h2>
      <p>
        Because Zamar Field is intended as an open-source project, we aim to be
        transparent about how the software works, what it stores locally, and
        which parts of the stack may interact with third-party services in later
        versions.
      </p>
      <h2>Third-party services</h2>
      <p>
        This website may rely on standard infrastructure providers such as
        hosting, analytics, or font delivery services in the future. When that
        happens, this page should be updated to reflect the actual services in
        use.
      </p>
      <h2>Children and sensitive contexts</h2>
      <p>
        Zamar Relief tools may eventually be used in humanitarian contexts where
        data sensitivity matters. Anyone deploying the software should assess the
        legal and operational requirements of their environment before collecting
        personal or identifying information.
      </p>
      <h2>Policy updates</h2>
      <p>
        This policy may change as the initiative grows, the project becomes more
        public, or the software adds new capabilities.
      </p>
    </LegalPage>
  );
}
